name: Mypy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: jbuchermn/pywm
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install mypy
        pip install -r requirements_mypy.txt
    - name: Generate pywm stubs
      run: |
        cd pywm
        stubgen -o ../pywm-stubs
    - name: mypy
      run: |
        MYPYPATH=$MYPYPATH:$GITHUB_WORKSPACE mypy newm
